# Generated by Django 5.0.4 on 2024-04-07 04:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroCliente',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.DecimalField(blank=True, decimal_places=0, max_digits=5)),
                ('bairro', models.CharField(choices=[('leandro_bezerra', 'Leandro Bezerra'), ('alto_sao_severino', 'Alto São Severino'), ('centro', 'Centro'), ('sebastiao_maltez', 'Sebastião Maltêz'), ('nestor_fernandes', 'Nestor Fernandes'), ('aroudo_maia', 'Aroudo Maia'), ('guiido_gurgel', 'Guido Gurgel'), ('nico_fernandes', 'Nicó Fernandes'), ('nova_caraubas', 'Nova Caraúbas')], max_length=30)),
                ('data_cadastro', models.DateField()),
            ],
        ),
    ]
